# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'name_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(200, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nameFilter = QtWidgets.QLineEdit(Dialog)
        self.nameFilter.setObjectName("nameFilter")
        self.verticalLayout_2.addWidget(self.nameFilter)
        self.nameList = QtWidgets.QListView(Dialog)
        self.nameList.doubleClicked.connect(Dialog.close)
        self.nameList.setObjectName("nameList")
        self.verticalLayout_2.addWidget(self.nameList)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "컨텐츠 정보 수정하기"))
        self.nameFilter.setPlaceholderText(_translate("Dialog", "Filter"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
